[package]
name = "nsv"
version = "0.3.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
async-trait = "0.1.74"
clap = { version = "4.4.8", features = ["derive", "env"] }
cursive = "0.21.1"
cursive_table_view = "0.15.0"
root = { workspace = true }
thiserror = { workspace = true }
tokio = { workspace = true }
