[package]
name = "util"
version.workspace = true
edition.workspace = true
license.workspace = true
authors.workspace = true

[dependencies]
tokio = { workspace = true }
reqwest = { workspace = true }
indicatif = { workspace = true }
futures-util = { workspace = true }
anyhow = { workspace = true }



[target.'cfg(windows)'.dependencies]
sevenz-rust = { workspace = true }
is_elevated = { workspace = true }

[target.'cfg(unix)'.dependencies]
tar = { workspace = true }
xz2 = { workspace = true }
